---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths: {}
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
